Gorm Implementation
abidkhan03/Go_training pull request #6
Opened 2023-01-23 05:23 UTC by abidkhan03

2023-01-23 12:01 UTC, mzeeshanali requested changes

2023-01-23 12:01 UTC, mzeeshanali commented on db/db.go
> +func Init() *gorm.DB {
```suggestion
func init() *gorm.DB {
```

2023-01-23 12:01 UTC, mzeeshanali commented on db/handlers.go
> +}
add empty line here

2023-01-23 12:01 UTC, mzeeshanali commented on db/gorm.go
> +
remove empty lines here

2023-01-23 12:01 UTC, mzeeshanali commented on db/gorm.go
> +	id := vars["id"]
use `go-chi`

2023-01-23 12:01 UTC, mzeeshanali commented on main.go
> +	DB := db.Init()
study about `init()` functions in golang

2023-01-23 12:01 UTC, mzeeshanali commented on db/gorm.go
> +
use `go-chi`

2023-01-23 12:01 UTC, mzeeshanali commented on db/db.go
> +	DB.AutoMigrate(&Object{})
please user docker to create the database

2023-01-23 12:01 UTC, mzeeshanali commented on .gitignore
> +.idea/
resolve conflict please

2023-01-23 12:11 UTC, abidkhan03 commented on .gitignore
> +.idea/
resolved

2023-01-24 13:56 UTC, mzeeshanali requested changes

2023-01-24 13:56 UTC, mzeeshanali commented on db/db.go
> +	//connStr := "host=localhost user=postgres password=admin123 dbname=gorm port=5432 sslmode=disable TimeZone=Asia/Karachi"
remove comments please

2023-01-24 13:56 UTC, mzeeshanali commented on db/db.go
> +}
add empty line here

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +	id := vars
```suggestion
	id := chi.URLParam(r, "id")
```

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +		fmt.Println(result.Error)
```suggestion
		log.Println(result.Error)
		 w.WriteHeader(http.StatusInternalServerError)
		return
```

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +	//defer r.Body.Close()
remove commented code

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +		fmt.Println(result.Error)
```suggestion
	if result := h.DB.Create(&object); result.Error != nil {
	 w.WriteHeader(http.StatusInternalServerError)
	 log.Println(result.Error)
	 return
```

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +	//json.Unmarshal(body, &updatedObject)
remove commented code

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +
remove empty line

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +		fmt.Println(result.Error)
```suggestion
        w.WriteHeader(http.StatusInternalServerError)
	log.Println(result.Error)
	return
```

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +
remove line here

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +	h.DB.Save(&object)
please check if it returns error.

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +
remove empty line here

2023-01-24 13:56 UTC, mzeeshanali commented on db/gorm.go
> +		fmt.Println(result.Error)
```suggestion
		log.Println(result.Error)
```

2023-01-25 06:36 UTC, abidkhan03 commented on db/gorm.go
> +	h.DB.Save(&object)
added condition to handle the error

2023-01-25 07:00 UTC, IsrarAliKhan requested changes
Remember to formate the whole code

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +}
Format the struct

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +	id := vars
not done yet

2023-01-25 07:00 UTC, IsrarAliKhan commented on init.sql
> +);
Add an empty line here

2023-01-25 07:00 UTC, IsrarAliKhan commented on init.sql
> +);
formate the sql file

2023-01-25 07:00 UTC, IsrarAliKhan commented on init.sql
> +);
make name `not null`

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/db.go
> +	}
```suggestion
	if err != nil {
		log.Println(err)
	}
	
	log.Println("Successfully connected to database..")
```

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/db.go
> +	}
In this way, if `DB` connectivity causes any issue, our `API` will not affect.

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/db.go
> +var err error
declare `err` variable in `init()` function

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +}
Make a directory named `models`. Create a file `object.go`. Move this `object` from `gorm.go` to `models/object.go`

Why do you think we should make a directory for `models/object.go`? Why not just `object.go`?
Answer me verbally :)

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +		log.Println(result.Error)
In case, when we receive an error message from the database, we are returning response code `200`.

In case of error, response code should be according to the error and respond body should contain proper error message

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +	json.NewDecoder(r.Body).Decode(&updatedObject)
same as above. validate the request

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +        log.Println(result.Error)
same as above. Log the error and respond accordingly

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +	id, _ := strconv.Atoi(vars)
validate the `id`

2023-01-25 07:00 UTC, IsrarAliKhan commented on db/gorm.go
> +		log.Println(result.Error)
same as above

2023-01-26 06:28 UTC, IsrarAliKhan requested changes

2023-01-26 06:28 UTC, IsrarAliKhan commented on db/gorm.go
> +package db
This file contains all the stuff related to request/response handling, validation and authorization, and database-related tasks. And this file is in `db` directory. `db` directory should only contain stuff related to the database. That's why it's not a good practice to add it here.

Create a directory named `handlers` outside the `db` directory. Move `gorm.go` from `db/` to `handlers/`. Rename this file with more specific and suitable name

2023-01-26 06:57 UTC, IsrarAliKhan approved these changes

2023-01-26 07:00 UTC, merged

2023-01-26 07:10 UTC, abidkhan03 commented
In this branch I worked on:
- Database connection
- Create Database using Docker Compose file
- Created Object's table
- Defined Simple CRUD operations' functions
- Get-all-objects to retrieve all data from database
- Get-object-by-id to retrieve a single object's record from database
- Create-object to add new record in table.
- Update-object-by-id
- Delete-object-by-id